export const Data = [
    {
        id: 1,
        title: "Urban House with Pool",
        location: "Los Angeles, CA, USA",
        price: 14000,
        bed: 4,
        bath: 3,
        sqft: 3400,
        year: 2020,
        type: "House",
        image: "./src/assets/properties/property1.jpeg",
        featured: true,
    },
    {
        id: 2,
        title: "Modern Apartment",
        location: "New York, NY, USA",
        price: 10500,
        bed: 2,
        bath: 2,
        sqft: 2200,
        year: 2022,
        type: "Apartment",
        image: "./src/assets/properties/property2.jpeg",
        featured: false,
    },
    {
        id: 3,
        title: "Corporate Office Space",
        location: "Chicago, IL, USA",
        price: 17000,
        bed: 0,
        bath: 2,
        sqft: 4500,
        year: 2019,
        type: "Office",
        image: "./src/assets/properties/property3.webp",
        featured: true,
    },
    {
        id: 4,
        title: "Luxury Villa Retreat",
        location: "Miami, FL, USA",
        price: 23000,
        bed: 5,
        bath: 4,
        sqft: 5300,
        year: 2021,
        type: "Villa",
        image: "./src/assets/properties/property4.jpeg",
        featured: false,
    },
    {
        id: 5,
        title: "Beach House Paradise",
        location: "Santa Barbara, CA, USA",
        price: 18000,
        bed: 4,
        bath: 3,
        sqft: 4200,
        year: 2022,
        type: "House",
        image: "./src/assets/properties/property1.jpeg",
        featured: true,
    },
    {
        id: 6,
        title: "Compact Urban Flat",
        location: "San Francisco, CA, USA",
        price: 9500,
        bed: 1,
        bath: 1,
        sqft: 1100,
        year: 2020,
        type: "Apartment",
        image: "./src/assets/properties/property2.jpeg",
        featured: false,
    },
    {
        id: 7,
        title: "Open Plan Office Floor",
        location: "Seattle, WA, USA",
        price: 16000,
        bed: 0,
        bath: 1,
        sqft: 5000,
        year: 2021,
        type: "Office",
        image: "./src/assets/properties/property3.webp",
        featured: false,
    },
    {
        id: 8,
        title: "Grand Mediterranean Villa",
        location: "Austin, TX, USA",
        price: 22000,
        bed: 6,
        bath: 5,
        sqft: 6000,
        year: 2019,
        type: "Villa",
        image: "./src/assets/properties/property4.jpeg",
        featured: true,
    },
    {
        id: 9,
        title: "Suburban Family Home",
        location: "Dallas, TX, USA",
        price: 12500,
        bed: 3,
        bath: 2,
        sqft: 2800,
        year: 2020,
        type: "House",
        image: "./src/assets/properties/property1.jpeg",
        featured: false,
    },
    {
        id: 10,
        title: "Luxury Sky Apartment",
        location: "Chicago, IL, USA",
        price: 20000,
        bed: 3,
        bath: 3,
        sqft: 3100,
        year: 2022,
        type: "Apartment",
        image: "./src/assets/properties/property2.jpeg",
        featured: false,
    },
    {
        id: 11,
        title: "Executive Business Hub",
        location: "Denver, CO, USA",
        price: 19500,
        bed: 0,
        bath: 3,
        sqft: 4700,
        year: 2021,
        type: "Office",
        image: "./src/assets/properties/property3.webp",
        featured: true,
    },
    {
        id: 12,
        title: "Lakefront Peaceful Villa",
        location: "Minneapolis, MN, USA",
        price: 21000,
        bed: 5,
        bath: 4,
        sqft: 5100,
        year: 2019,
        type: "Villa",
        image: "./src/assets/properties/property4.jpeg",
        featured: false,
    },
    {
        id: 13,
        title: "Countryside House",
        location: "Nashville, TN, USA",
        price: 12000,
        bed: 4,
        bath: 3,
        sqft: 3600,
        year: 2020,
        type: "House",
        image: "./src/assets/properties/property1.jpeg",
        featured: true,
    },
    {
        id: 14,
        title: "High Rise Apartment",
        location: "Philadelphia, PA, USA",
        price: 14500,
        bed: 2,
        bath: 2,
        sqft: 2400,
        year: 2021,
        type: "Apartment",
        image: "./src/assets/properties/property2.jpeg",
        featured: false,
    },
    {
        id: 15,
        title: "Business Bay Office",
        location: "Atlanta, GA, USA",
        price: 18000,
        bed: 0,
        bath: 2,
        sqft: 4000,
        year: 2022,
        type: "Office",
        image: "./src/assets/properties/property3.webp",
        featured: false,
    },
    {
        id: 16,
        title: "Elite Mountain Villa",
        location: "Salt Lake City, UT, USA",
        price: 23500,
        bed: 6,
        bath: 5,
        sqft: 6200,
        year: 2019,
        type: "Villa",
        image: "./src/assets/properties/property4.jpeg",
        featured: true,
    },
    {
        id: 17,
        title: "Twin Garage House",
        location: "Phoenix, AZ, USA",
        price: 13000,
        bed: 3,
        bath: 2,
        sqft: 3000,
        year: 2021,
        type: "House",
        image: "./src/assets/properties/property1.jpeg",
        featured: false,
    },
    {
        id: 18,
        title: "Central Studio Apartment",
        location: "San Diego, CA, USA",
        price: 9000,
        bed: 1,
        bath: 1,
        sqft: 1000,
        year: 2022,
        type: "Apartment",
        image: "./src/assets/properties/property2.jpeg",
        featured: false,
    },
    {
        id: 19,
        title: "Open Layout Office",
        location: "Orlando, FL, USA",
        price: 15000,
        bed: 0,
        bath: 1,
        sqft: 3500,
        year: 2020,
        type: "Office",
        image: "./src/assets/properties/property3.webp",
        featured: false,
    },
    {
        id: 20,
        title: "Tropical Island Villa",
        location: "Honolulu, HI, USA",
        price: 26000,
        bed: 5,
        bath: 4,
        sqft: 5800,
        year: 2021,
        type: "Villa",
        image: "./src/assets/properties/property4.jpeg",
        featured: true,
    },
    {
        id: 21,
        title: "Lawnside House",
        location: "Portland, OR, USA",
        price: 13500,
        bed: 3,
        bath: 2,
        sqft: 2900,
        year: 2019,
        type: "House",
        image: "./src/assets/properties/property1.jpeg",
        featured: false,
    },
    {
        id: 22,
        title: "Green Apartment",
        location: "Boulder, CO, USA",
        price: 11500,
        bed: 2,
        bath: 1,
        sqft: 2000,
        year: 2020,
        type: "Apartment",
        image: "./src/assets/properties/property2.jpeg",
        featured: false,
    },
    {
        id: 23,
        title: "City Business Center",
        location: "Houston, TX, USA",
        price: 17000,
        bed: 0,
        bath: 2,
        sqft: 4300,
        year: 2022,
        type: "Office",
        image: "./src/assets/properties/property3.webp",
        featured: true,
    },
    {
        id: 24,
        title: "Private Cliffside Villa",
        location: "Malibu, CA, USA",
        price: 24000,
        bed: 6,
        bath: 5,
        sqft: 6400,
        year: 2021,
        type: "Villa",
        image: "./src/assets/properties/property4.jpeg",
        featured: false,
    },
];
